# Generated by Django 4.0.4 on 2022-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_info',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='store',
            name='currency',
        ),
    ]
