# Generated by Django 4.0.3 on 2022-05-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.RemoveField(
            model_name='store_staff',
            name='slugified_username',
        ),
        migrations.AlterField(
            model_name='store_staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
