# Generated by Django 4.0.5 on 2022-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
