# Generated by Django 4.0.3 on 2022-05-22 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_store_name_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="store_staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="user-profile-images/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("password", models.CharField(max_length=100)),
                ("password2", models.CharField(max_length=100)),
                ("store", models.CharField(choices=[], max_length=150)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Staff",
                "verbose_name_plural": " Store Staffs",
            },
        ),
    ]
