# Generated by Django 4.0.5 on 2022-07-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_store_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_staff',
            name='user',
        ),
    ]
