# Generated by Django 4.0.4 on 2022-06-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.currency'),
        ),
    ]
