# Generated by Django 4.0.6 on 2022-08-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_store_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
