# Generated by Django 4.0.3 on 2022-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_store_staff_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_staff',
            name='store',
            field=models.CharField(choices=[('Chryz Store', 'Chryz Store'), ('code store', 'code store')], max_length=150),
        ),
    ]
