# Generated by Django 4.0.4 on 2022-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_store_bank_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="flutterwave_code",
            field=models.CharField(default="hello", max_length=10),
        ),
    ]
