# Generated by Django 4.0.3 on 2022-05-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_store_creator_alter_store_staff_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user-profile-images/'),
        ),
    ]
