# Generated by Django 4.0.4 on 2022-06-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_currency_flutterwave_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="flutterwave_code",
            field=models.CharField(max_length=10),
        ),
    ]
