# Generated by Django 4.0.3 on 2022-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_store_staff_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(blank=True, null=True, upload_to='store-images/'),
        ),
    ]
