# Generated by Django 4.0.3 on 2022-05-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_store_staff_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_staff',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
    ]
