# Generated by Django 4.0.3 on 2022-05-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_store_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_staff',
            name='store',
            field=models.CharField(choices=[('code store', 'code store'), ('Chryz Store', 'Chryz Store')], max_length=150),
        ),
    ]
