# Generated by Django 4.0.4 on 2022-06-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_currency_flutterwave_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bank_info",
            name="currency",
        ),
    ]
