# Generated by Django 4.0.3 on 2022-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_store_staff_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_staff',
            name='store',
            field=models.CharField(max_length=150),
        ),
    ]
