# Generated by Django 4.0.3 on 2022-05-04 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_store_description_user_store_image_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('slugified_username', models.SlugField(max_length=255, unique=True)),
                ('avatar', models.ImageField(null=True, upload_to='user-profile-images/')),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_store', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_staffs_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
