# Generated by Django 4.0.4 on 2022-06-15 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_bank_info_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank_info",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.store",
            ),
        ),
    ]
