# Generated by Django 4.0.4 on 2022-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_store_staff_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(upload_to='store-images/'),
        ),
    ]
