# Generated by Django 4.0.4 on 2022-06-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_bank_info_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank_info",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.store"
            ),
        ),
    ]
