# Generated by Django 4.0.6 on 2022-08-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_wallet_transanction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_transanction',
            name='account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
