# Generated by Django 4.0.4 on 2022-05-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_store_store_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store_staff",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store",
                to="account.store",
            ),
        ),
    ]
