# Generated by Django 4.0.3 on 2022-05-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_store_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_staff',
            name='user',
        ),
        migrations.AlterField(
            model_name='store_staff',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
