# Generated by Django 4.0.3 on 2022-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_store_staff_user_alter_store_staff_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_staff',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='store_staff',
            name='password2',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
