# Generated by Django 4.0.4 on 2022-06-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_bank_info_store"),
    ]

    operations = [
        migrations.DeleteModel(
            name="store_bank_details",
        ),
    ]
