# Generated by Django 4.0.6 on 2022-08-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_wallet_transanction_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet_transanction',
            old_name='account',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='wallet_transanction',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
