# Generated by Django 4.0.3 on 2022-05-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_store_staff_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_image',
            field=models.ImageField(default='store-images/default.jpg', upload_to='store-images/'),
        ),
    ]
