# Generated by Django 4.0.4 on 2022-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_delete_store_bank_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank_info",
            name="bank_code",
            field=models.CharField(default="", max_length=10),
        ),
    ]
