# Generated by Django 4.0.4 on 2022-05-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_store_staff_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
