# Generated by Django 4.0.4 on 2022-05-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_currency_options_store_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='account.currency'),
        ),
    ]
