# Generated by Django 4.0.3 on 2022-05-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
