# Generated by Django 4.0.4 on 2022-05-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_store_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='currency_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='currency_symbol',
            new_name='symbol',
        ),
    ]
