# Generated by Django 4.0.6 on 2022-08-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_wallet_transanction_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_transanction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.wallet'),
        ),
        migrations.AlterField(
            model_name='withdrawal_transanction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.wallet'),
        ),
    ]
