# Generated by Django 4.0.4 on 2022-06-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_bank_info_currency_alter_store_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='store_currency', to='account.currency'),
        ),
    ]
