# Generated by Django 4.0.4 on 2022-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_store_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='currency',
        ),
        migrations.AddField(
            model_name='currency',
            name='store',
            field=models.ManyToManyField(related_name='store_currency', to='account.store'),
        ),
    ]
