# Generated by Django 4.1 on 2022-08-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_store_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.currency"
            ),
        ),
    ]
