# Generated by Django 4.0.4 on 2022-06-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_currency_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.ManyToManyField(blank=True, to='account.currency'),
        ),
    ]
