# Generated by Django 4.1 on 2022-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_store_address_alter_store_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="country_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="store",
            name="state_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
