# Generated by Django 4.0.4 on 2022-06-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_currency_store_store_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='currency',
        ),
    ]
