# Generated by Django 4.1 on 2022-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_store_country_code_store_state_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank_info",
            name="account_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bank_info",
            name="bank_name",
            field=models.CharField(max_length=200),
        ),
    ]
