# Generated by Django 4.0.4 on 2022-06-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_store_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_info',
            name='currency',
        ),
    ]
