# Generated by Django 4.1 on 2022-08-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_shipping_company_store_shipping_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping_company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
