# Generated by Django 4.1 on 2022-08-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_shipping_company_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping_company",
            name="email",
            field=models.EmailField(default="hi@gmail.com", max_length=254),
        ),
    ]
