# Generated by Django 4.0.3 on 2022-05-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(default='uouos', max_length=300),
        ),
    ]
