# Generated by Django 4.0.3 on 2022-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.CharField(choices=[('code store', 'code store')], max_length=150),
        ),
    ]
