# Generated by Django 4.0.5 on 2022-07-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
    ]
