# Generated by Django 4.0.3 on 2022-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.CharField(choices=[('Chryz Store', 'Chryz Store'), ('code store', 'code store')], max_length=150),
        ),
    ]
