# Generated by Django 4.1 on 2022-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_remove_address_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="state_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
