# Generated by Django 4.0.3 on 2022-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_address_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='lagos', max_length=200, verbose_name='City'),
        ),
    ]
