# Generated by Django 4.0.4 on 2022-05-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_store_staff_store'),
        ('customer', '0006_alter_customer_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='account.store'),
        ),
    ]
