# Generated by Django 4.0.4 on 2022-06-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_order_payment_shipping_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="postcode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
