# Generated by Django 4.0.6 on 2022-08-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_wallet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
