# Generated by Django 4.0.4 on 2022-06-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_payment_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
    ]
