# Generated by Django 4.0.6 on 2022-08-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet_transanction',
            name='withdraw',
        ),
    ]
