# Generated by Django 4.1 on 2022-08-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_shipping_method_country_and_more"),
        ("payment", "0006_remove_wallet_transanction_withdraw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="shipping_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.shipping_method",
            ),
        ),
    ]
