# Generated by Django 4.1.1 on 2022-09-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_address_country_code_address_state_code"),
        ("payment", "0007_alter_payment_shipping_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="use_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.address",
            ),
        ),
    ]
