# Generated by Django 4.1.1 on 2024-01-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_shipping_method'),
        ('payment', '0009_alter_wallet_transanction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.shipping_method'),
        ),
    ]
