# Generated by Django 4.0.5 on 2022-06-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_method',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shipping_method',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shipping_method',
            name='store',
        ),
    ]
