# Generated by Django 4.0.3 on 2022-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_by",
            field=models.CharField(
                choices=[("code store", "code store")], max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="created_by",
            field=models.CharField(
                choices=[("code store", "code store")], max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(choices=[("laptop", "laptop")], max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.CharField(
                choices=[("code store", "code store")], max_length=150
            ),
        ),
    ]
