# Generated by Django 4.0.3 on 2022-05-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_created_by_alter_coupon_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.CharField(choices=[('Chryz Store', 'Chryz Store'), ('code store', 'code store')], max_length=150),
        ),
    ]
