# Generated by Django 4.0.5 on 2022-06-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('app', '0002_remove_shipping_method_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_method',
            name='location',
            field=models.CharField(default='hey', max_length=250),
        ),
        migrations.AddField(
            model_name='shipping_method',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipping_method',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_method', to='account.store'),
        ),
    ]
