# Generated by Django 3.2.4 on 2022-02-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_slugified_username_user_slugified_store_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
