# Generated by Django 4.0.5 on 2022-06-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('app', '0003_shipping_method_location_shipping_method_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_method',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shipping_method',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_method', to='account.store'),
        ),
    ]
