# Generated by Django 4.0.3 on 2022-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=255),
        ),
    ]
