# Generated by Django 4.0.4 on 2022-06-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
    ]
