# Generated by Django 4.0.3 on 2022-05-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.CharField(choices=[('code store', 'code store'), ('Chryz Store', 'Chryz Store')], max_length=150),
        ),
    ]
