# Generated by Django 4.0.3 on 2022-05-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coupon_users_alter_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.AlterField(
            model_name='product',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
