# Generated by Django 4.0.3 on 2022-05-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_coupon_created_by_remove_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.CharField(choices=[('code store', 'code store'), ('Chryz Store', 'Chryz Store')], default='heruierey', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(choices=[('code store', 'code store'), ('Chryz Store', 'Chryz Store')], default='heruie', max_length=150),
        ),
    ]
