# Generated by Django 4.0.6 on 2022-07-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_last_24_hours_sales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='last_24_hours_sales',
            options={'verbose_name_plural': 'last_24_hours_sales'},
        ),
    ]
