# Generated by Django 4.0.3 on 2022-05-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_coupon_active_alter_product_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coupon',
        ),
    ]
