# Generated by Django 4.0.3 on 2022-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_coupon_created_by_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.CharField(choices=[('code store', 'code store'), ('Chryz Store', 'Chryz Store')], max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.CharField(choices=[('code store', 'code store'), ('Chryz Store', 'Chryz Store')], max_length=150),
        ),
    ]
