# Generated by Django 3.2.4 on 2022-02-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_product_order_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product_order_count",
            options={
                "ordering": ("-order_count",),
                "verbose_name_plural": "Product Order Counts",
            },
        ),
    ]
