# Generated by Django 4.0.3 on 2022-05-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_coupon_created_by_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.CharField(choices=[('Chryz Store', 'Chryz Store'), ('code store', 'code store')], max_length=150),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.CharField(choices=[('Chryz Store', 'Chryz Store'), ('code store', 'code store')], max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.CharField(choices=[('Chryz Store', 'Chryz Store'), ('code store', 'code store')], max_length=150),
        ),
    ]
