# Generated by Django 4.0.4 on 2022-05-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_store_store_image'),
        ('app', '0007_alter_category_created_by_alter_coupon_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.store'),
        ),
    ]
