# Generated by Django 4.0.4 on 2022-06-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_review_email_review_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
    ]
