# Generated by Django 3.2.4 on 2022-02-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_order_count_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Product_Order_Count',
        ),
    ]
