# Generated by Django 4.0.4 on 2022-06-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_review_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
