# Generated by Django 3.2.4 on 2022-02-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20220223_1503"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="order_count",
        ),
    ]
