# Generated by Django 4.0.4 on 2022-06-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_review_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
