# Generated by Django 4.0.4 on 2022-06-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_review_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-created",), "verbose_name_plural": "Reviews"},
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
