# Generated by Django 4.0.4 on 2022-06-01 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_category_created_by_alter_coupon_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="percentage",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
