# Generated by Django 4.1 on 2022-08-15 10:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_remove_address_city"),
        ("account", "0017_remove_wallet_transanction_store_and_more"),
        ("app", "0012_customers_monthly"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store_Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ManyToManyField(blank=True, to="customer.customer"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.store"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Store Newsletter",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("body", ckeditor.fields.RichTextField()),
                (
                    "store_newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.store_newsletter",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "A Store newsletters",
            },
        ),
    ]
