# Generated by Django 3.2.4 on 2022-02-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
