# Generated by Django 4.0.4 on 2022-06-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_bank_info_currency_alter_store_currency"),
        ("app", "0013_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.currency"
            ),
        ),
    ]
