# Generated by Django 4.1 on 2022-08-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_rename_customer_store_newsletter_customers"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="updated",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
