# Generated by Django 3.2.4 on 2022-03-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_unit', to='app.productunit'),
        ),
    ]
