# Generated by Django 4.1 on 2022-08-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_newsletter_created_alter_newsletter_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="store_newsletter",
            new_name="store",
        ),
    ]
