# Generated by Django 4.1 on 2022-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_rename_store_newsletter_newsletter_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
