# Generated by Django 4.1 on 2022-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_product_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipping_method",
            name="location",
        ),
        migrations.RemoveField(
            model_name="shipping_method",
            name="store",
        ),
        migrations.AddField(
            model_name="shipping_method",
            name="country",
            field=models.CharField(default="hi", max_length=200),
        ),
        migrations.AddField(
            model_name="shipping_method",
            name="state",
            field=models.CharField(default="hi", max_length=200),
        ),
    ]
