# Generated by Django 4.1 on 2022-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_remove_shipping_method_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping_method",
            name="country",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="shipping_method",
            name="state",
            field=models.CharField(max_length=200),
        ),
    ]
