# Generated by Django 4.1 on 2022-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_shipping_method_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping_method",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
