# Generated by Django 4.1 on 2022-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_shipping_method_flutterwave_fund_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipping_method",
            name="country_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="shipping_method",
            name="state_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
