# Generated by Django 4.1 on 2022-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_shipping_method_country_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipping_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("account_name", models.CharField(max_length=300)),
                ("bank_code", models.CharField(max_length=10)),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
            ],
        ),
    ]
