# Generated by Django 4.1 on 2022-08-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_shipping_method_shipping_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipping_method",
            name="shipping_company",
        ),
    ]
