# Generated by Django 4.1 on 2022-08-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_shipping_company_store_shipping_company"),
        ("app", "0029_shipping_method_shipping_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping_method",
            name="shipping_company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.shipping_company",
            ),
        ),
        migrations.DeleteModel(
            name="Shipping_Company",
        ),
    ]
