# Generated by Django 4.1 on 2022-08-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alter_shipping_method_shipping_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipping_method",
            name="shipping_company",
        ),
    ]
