# Generated by Django 4.1.1 on 2022-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_shipping_method_shipping_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ("-created",),
                "verbose_name_plural": "A Store newsletters",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="normal_price",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
