# Generated by Django 4.1.1 on 2022-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_coupon_options_alter_newsletter_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="normal_price",
            field=models.PositiveIntegerField(
                default=models.PositiveIntegerField(default=1)
            ),
        ),
    ]
