# Generated by Django 4.1.1 on 2022-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_product_normal_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="normal_price",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
