# Generated by Django 4.0.3 on 2022-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
