# Generated by Django 4.0.5 on 2022-07-02 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringsubscriptiondata",
            name="user",
        ),
        migrations.AddField(
            model_name="recurringsubscriptiondata",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.store",
            ),
        ),
    ]
