# Generated by Django 4.0.5 on 2022-07-02 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0004_remove_subscription_user_subscription_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringsubscriptiondata",
            name="store",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="store",
        ),
        migrations.AddField(
            model_name="recurringsubscriptiondata",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
