# Generated by Django 4.0.5 on 2022-07-02 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0005_remove_recurringsubscriptiondata_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringsubscriptiondata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
