# Generated by Django 4.0.3 on 2022-06-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_bank_info_bank_code"),
        ("subscriptions", "0005_subscription_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.currency"
            ),
        ),
    ]
