# Generated by Django 4.0.3 on 2022-06-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_ref_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='price',
            new_name='amount',
        ),
    ]
