# Generated by Django 4.0.3 on 2022-06-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_timeline',
            name='mail_remainder',
            field=models.BooleanField(default=False),
        ),
    ]
