# Generated by Django 4.0.3 on 2022-06-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_recurringsubscriptiondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringSubscriptionData',
        ),
    ]
