# Generated by Django 4.0.3 on 2022-06-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringpayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringsubscriptiondata',
            name='charge',
            field=models.BooleanField(default=True),
        ),
    ]
