# Generated by Django 4.0.3 on 2022-06-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringpayment', '0002_recurringsubscriptiondata_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringsubscriptiondata',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
