# Generated by Django 4.0.3 on 2022-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringpayment', '0003_recurringsubscriptiondata_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringsubscriptiondata',
            name='currency',
            field=models.CharField(max_length=6),
        ),
    ]
