# Generated by Django 4.0.4 on 2022-06-02 21:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0014_alter_product_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0002_remove_orderitem_order_remove_orderitem_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField(default=0)),
                ("billing_status", models.BooleanField(default=False)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("product", models.ManyToManyField(blank=True, to="app.product")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
