# Generated by Django 4.0.4 on 2022-06-07 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
