# Generated by Django 4.0.4 on 2022-06-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_bank_info_currency_alter_store_currency'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='account.store'),
        ),
    ]
