# Generated by Django 4.0.4 on 2022-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_remove_order_product_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
