# Generated by Django 4.0.4 on 2022-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
