# Generated by Django 4.0.4 on 2022-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_alter_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency_name",
            field=models.CharField(default="USD", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="currency_symbol",
            field=models.CharField(default="$", max_length=10),
        ),
    ]
