# Generated by Django 4.0.4 on 2022-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_currency_name_order_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency_symbol',
            field=models.CharField(max_length=10),
        ),
    ]
