# Generated by Django 4.0.3 on 2022-06-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_currency_name_order_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail_remainder',
            field=models.BooleanField(default=False),
        ),
    ]
